export { default as LoginPage } from './auth/login'
export { default as AdminPage } from './admin'
export { default as ExamPage } from './admin/exam'
export { default as StudentExamAttemptPage } from './exam/attempt'
export { default as StudentStartAttemptPage } from './exam/attempt/start'
export { default as StudentExamPage } from './exam'
export { default as NotFoundPage } from './error/page-not-found'
export { default as QuestionPage } from './admin/question'
